apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-cluster-deployment
  namespace: k8-cluster
  labels:
    app: k8-cluster

spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-cluster

  template:
    metadata:
      namespace: k8-cluster
      labels:
        app: k8-cluster

    spec:
      containers:
      - name: k8-cluster
        image: localhost:5001/k8_cluster:0.1.0
        tty: true
        stdin: true
        ports:
        - containerPort: 4000
        env:
        - name: PHX_HOST
          value: localhost
        - name: PHX_PORT
          value: '4000'
        - name: DNS_CLUSTER_QUERY
          value: ''
        - name: SECRET_KEY_BASE 
          valueFrom:
            secretKeyRef:
              name: k8-cluster-secret
              key: key_base
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
