kind: Service
apiVersion: v1
metadata:
  name: k8-cluster-service
  namespace: k8-cluster
spec:
  selector:
    app: k8-cluster
  ports:
    - name: k8-cluster-web 
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name: k8-cluster-headless-service
  namespace: k8-cluster
spec:
  selector:
    app: k8-cluster
  type: ClusterIP
  clusterIP: None
